apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  labels:
    api: tor
    kubebuilder.k8s.io: master
  name: tor-system
spec: {}
status: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    api: tor
    kubebuilder.k8s.io: master
  name: tor-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - tor.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    api: tor
    kubebuilder.k8s.io: master
  name: tor-rolebinding
  namespace: tor-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tor-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: tor-system
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    api: tor
    kubebuilder.k8s.io: master
  name: onionservices.tor.k8s.io
spec:
  group: tor.k8s.io
  names:
    kind: OnionService
    plural: onionservices
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            extraConfig:
              type: string
            ports:
              items:
                properties:
                  name:
                    type: string
                  publicPort:
                    format: int32
                    type: integer
                  targetPort:
                    format: int32
                    type: integer
                type: object
              type: array
            privateKeySecret:
              properties:
                key:
                  type: string
                name:
                  type: string
              type: object
            selector:
              type: object
            version:
              enum:
              - 0
              - 2
              - 3
              format: int32
              type: integer
          type: object
        status:
          properties:
            hostname:
              type: string
            targetClusterIP:
              type: string
          type: object
      type: object
  version: v1alpha1
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    api: tor
    control-plane: controller-manager
    kubebuilder.k8s.io: master
  name: tor-controller-manager-service
  namespace: tor-system
spec:
  clusterIP: None
  selector:
    api: tor
    control-plane: controller-manager
    kubebuilder.k8s.io: master
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    api: tor
    control-plane: controller-manager
    kubebuilder.k8s.io: master
  name: tor-controller-manager
  namespace: tor-system
spec:
  replicas: 1
  selector:
    matchLabels:
      api: tor
      control-plane: controller-manager
      kubebuilder.k8s.io: master
  serviceName: tor-controller-manager-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        api: tor
        control-plane: controller-manager
        kubebuilder.k8s.io: master
    spec:
      containers:
      - args:
        - --install-crds=false
        command:
        - /root/controller-manager
        image: nishedcob/tor-controller-manager:master
        name: controller-manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
  updateStrategy: {}
status:
  replicas: 0
